name: sozEbay
description: Medical Dictionary
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Utilities
  flutter_svg: ^1.1.6

  # Localization
  easy_localization: ^3.0.1

  # State Management
  provider: ^6.0.4

  # Navigation
  auto_route: ^5.0.1

  # Local Base
  hive_flutter: ^1.1.0
  kartal: ^2.7.0

  # Alarm Manager
  flutter_local_notifications: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/
    - assets/words/words.json
    - assets/words/notification.json

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/Regular.otf
          weight: 400
        - asset: assets/fonts/Medium.otf
          weight: 500
        - asset: assets/fonts/MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Semibold.otf
          weight: 600
        - asset: assets/fonts/Bold.otf
          weight: 700